---
title: "Periodic GPs"
author: "FZ"
date: "3/23/2021"
output: rmarkdown::github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Estimating the period:

```{r}
library(tidyverse)
library(rstan)
library(bayesplot)

rstan_options(auto_write = TRUE)
```


```{stan, output.var="gp_pred"}

functions {
  
  int is_week(int d) {
    if(d == 6 || d == 7)
      return 0;
    else
      return 1;
  }
  
  real exp_kern(real x1, real x2, real alpha, real rho){
    return square(alpha) * exp(-fabs(x1 - x2) / square(rho));
  }

  real periodic_kern(real x1, real x2, real alpha, real rho, real p){
    real nom = square(sin(pi()*(x1 - x2)/p));
    return square(alpha) * exp(-nom / square(rho));
  }
  
}

data {
  int<lower=1> N;
  real x[N];
  vector[N] y;
}

transformed data {
  vector[N] mu = rep_vector(0, N);
}

parameters {
  real<lower=0> rho;
  real<lower=0> alpha;
  real<lower=0> p;
  real<lower=0> sigma;
}

model {
  matrix[N, N] L_K;
  matrix[N, N] K;
  real sq_sigma = square(sigma);

  for (r in 1:N){
    for(c in 1:N){
      K[r, c] = periodic_kern(x[r], x[c], alpha, rho, p);
    }
  }
  
  // diagonal elements
  for (n in 1:N)
    K[n, n] = K[n, n] + sq_sigma;

  L_K = cholesky_decompose(K);

  rho ~ inv_gamma(5, 5);
  alpha ~ std_normal();
  p ~ uniform(0, 5);
  sigma ~ std_normal();

  y ~ multi_normal_cholesky(mu, L_K);
}

generated quantities { 
  int is_w = is_week(6);
}

```

## Periodic Kernel 


```{r}

N <- 50
x <- seq(0, 10, length.out = N)
y <- sin(x) + runif(N, 0, 0.5)

gp_pred_data <- list(N = N, x = x, y = y)

tibble(N, x, y) %>%
  ggplot(aes(x, y)) +
  geom_point()

```


```{r}

fit_pred <- sampling(gp_pred, data = gp_pred_data, 
                     iter = 2000, 
                     control = list(max_treedepth = 10))
```

### Divergent transitions:

```{r}

pairs(fit_pred, pars = c("rho", "alpha", "p"), las = 1)

```
  
```{r}

fit_pred

```

```{r}

mcmc_areas(
  fit_pred, 
  pars = c("rho", "alpha", "p"), 
  prob = 0.8, # 80% intervals
  prob_outer = 0.99, # 99%
  point_est = "mean"
)

```