---
title: "sum of gps"
author: "FZ"
date: "3/24/2021"
output: rmarkdown::github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Sum of GPs

```{r}

library(tidyverse)
library(rstan)
library(bayesplot)
library(lubridate)

rstan_options(auto_write = TRUE)

```

## Sum of GPs


```{stan, output.var="gp_sum"}

functions {
  
  int is_weekday(int d) {
    if(d == 6 || d == 7)
      return 0;
    else
      return 1;
  }
  
  real exp_quad_kern(real x1, real x2, real alpha, real rho){
    return square(alpha) * exp(-square(x1 - x2) / square(rho));
  }
  
  real exp_kern(real x1, real x2, real alpha, real rho){
    return square(alpha) * exp(-fabs(x1 - x2) / square(rho));
  }

  real periodic_kern(real x1, real x2, real alpha, real rho, real p){
    real nom = square(sin(pi()*(x1 - x2)/p));
    return square(alpha) * exp(-nom / square(rho));
  }
  
}

data {
  int<lower=1> N;
  real x[N];
  vector[N] y;
}

transformed data {
  vector[N] mu = rep_vector(0, N);
}

parameters {
  // long-term trends:
  real<lower=0> rho_lt;
  real<lower=0> alpha_lt;
  // short-term trends:
  real<lower=0> rho_st;
  real<lower=0> alpha_st;
  // weekly-quasi-periodic patterns:
  real<lower=0> rho_wqp1;
  real<lower=0> rho_wqp2;
  real<lower=0> alpha_wqp;
  // yearly seasonal pattern: 
  //real<lower=0> rho_ys1;real<lower=0> rho_ys2;real<lower=0> alpha_ys;
  
  real<lower=0> sigma;
}

model {
  matrix[N, N] L_K;
  matrix[N, N] K;
  real sq_sigma = square(sigma);

  for (r in 1:N){
    for(c in 1:N){
      K[r, c] = exp_quad_kern(x[r], x[c], alpha_lt, rho_lt) +
                exp_quad_kern(x[r], x[c], alpha_st, rho_st) +
      exp_quad_kern(x[r], x[c], 1, rho_wqp1) *
      periodic_kern(x[r], x[c], alpha_wqp, rho_wqp2, 7);
    }
  }
  
  // diagonal elements
  for (n in 1:N)
    K[n, n] = K[n, n] + sq_sigma;

  L_K = cholesky_decompose(K);

  rho_lt ~ inv_gamma(5, 5);
  alpha_lt ~ std_normal();
  rho_st ~ inv_gamma(5, 5);
  alpha_st ~ std_normal();
  sigma ~ std_normal();

  rho_wqp1 ~ inv_gamma(5, 5);
  rho_wqp2 ~ inv_gamma(5, 5);
  alpha_wqp ~ std_normal();
  
  y ~ multi_normal_cholesky(mu, L_K);
}

```

## Data:

```{r}

births <- read_csv("./births.csv") %>%
  na.omit() %>%
  filter(day != 99) %>%
  unite(date, year, month, day, sep = "-") %>%
  mutate(date = ymd(date), y_day = yday(date), 
         gender = case_when(gender == "F" ~ "female", TRUE ~ "male")) %>%
  na.omit() %>%
  pivot_wider(names_from = gender, values_from = births) %>%
  mutate(births = female + male) %>%
  na.omit()

```


```{r}

births %>%
  ggplot(aes(date, births)) +
  geom_point() +
  geom_smooth() +
  labs(x = "Day of the year", y = "Number of births")

births %>%
  group_by(y_day) %>%
  summarise(births = mean(births)) %>%
  ggplot(aes(y_day, births)) +
  geom_line() +
  geom_smooth() +
  labs(x = "Day of the year", y = "Number of births")

```


```{r}

births_1969 <- births %>% 
  filter(year(date) == 1969) %>%
  mutate(y_day = yday(date))

births_1969 %>% filter(is.na(births))

N <- dim(births_1969)[1]

births_data <- list(N=N, x=births_1969$y_day, y=births_1969$births)

births_data

```
```{r}

fit_pred <- sampling(gp_sum, data = births_data, 
                     iter = 2000, control = list(max_treedepth = 10))

```

```{r}

fit_pred

```